### ISSUE TITLE
Support for EPSG 4979

### ISSUE THREAD

**Issue by GraemeKerry** [GeoLatte/geolatte-geom#100]
Hi,

I am using geolatte-geom 1.3.0 as part of a Hibernate Spatial stack to persist JTS geometries to a PostGIS database.

This works fine for 2D geometries using a SRID of 4326. However I am now trying to persist 3D JTS geometries (X, Y and Z) using a SRID of 4979. This SRID is not reaching the database and the WKB that goes across in the SQL doesn't have the SRID in it.

I have debugged the code and think this may be caused by the fact geo latte-geom doesn't include 4979 in it's spatial_ref_sys.txt file that is used during JTS to geo latte geometry conversion (JTS.java). 4979 is looked up, not found and a default of -1 is assigned. 

I found the following link which reports a similar issue that was fixed in 1.1.0.
https://hibernate.atlassian.net/browse/HHH-11283?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&showAll=true

Am I doing something wrong? Should 4979 work? If not is there another SRID I could correctly apply to model WGS84 geometries with a height?

Thanks

Graeme

**Comment by maesenka** [comment]
You should use 4326. Because so many data out there uses 2D reference
systems with 3D data that geolatte-geom will automatically add a third
(vertical) dimension for XYZ data.

Regards,

Karel

**Comment by GraemeKerry** [comment]
Thanks for the quick reply Karel, I'll give that a try.
