### ISSUE TITLE
Add CRS EPSG:4467 to spatial_ref_sys.txt file

### ISSUE THREAD

**Issue by fabianm536** [GeoLatte/geolatte-geom#118]
CRS EPSG:4476 is not present in spatial_ref_sys.txt file. 

There is a way to add this CRS to list or create it?

Thanks

**Comment by maesenka** [comment]
I was looking at this issue, but I can't find a definition for EPSG:4476. I can't find it in [the EPSG database](https://epsg.org/home.html). You sure you have the right code? Do you have a definition?

**Comment by fabianm536** [comment]
The correct code is [EPSG:4467](https://epsg.org/crs_4467/RGSPM06-UTM-zone-21N.html?sessionkey=xiqcyqc5xj)

**Comment by maesenka** [comment]
4467 is in the new spatial_ref_sys
