### ISSUE TITLE
Userguide

### ISSUE THREAD

**Issue by AadityaPatanjali** [GeoLatte/geolatte-geom#120]
I can't seem to find a good user guide for the newest library version. Can someone point me to one?

Eg: 1. How do I make a 3d point in EPSG:32614? I know one way is to convert wkt to a point, but what would be the correct way? Geometries.mkPoint seems to work with G2D, but not G3D.
2. Support for GeometryDeserializer for jackson seems to have been dropped.

**Comment by maesenka** [comment]
The README covers these questions. Therefore closing this issue.
