### ISSUE TITLE
CrsRegistry warnings when working with JST 1.18

### ISSUE THREAD

**Issue by bbehrang** [GeoLatte/geolatte-geom#126]
Upon persisting JTS Geometry types(tested with Polygon and Point) into a postgres database using hibernate, even though the geometry is successfully saved to the database, I receive multiple warnings from _org.geolatte.geom.crs.CrsRegistry_ in the form of "Can't parse srid ****()". Is this an issue with the dependency versions that I'm using? 
I have included a log file below.

Versions:
geolatte-geom: 1.7.0
JTS core: 1.18.0
hibernate: 5.4.28.Final

Geometry: POLYGON ((30.473824 50.411819, 30.476112 50.400392, 30.495567 50.399906, 30.497093 50.412792, 30.473824 50.411819))

[warnings.log](https://github.com/GeoLatte/geolatte-geom/files/5988827/warnings.log)

**Comment by maesenka** [comment]
Those messages are harmless, and It has nothing to do with the JTS dependency.

It turns out that the spatial refs file (which I copy from the Postgis project) contains a type of CRS that Geolatte doesn't know how to parse. Hence the errors. 

I will filter these out in a next version.
