### ISSUE TITLE
CoordinateReferenceSystem cannot be cast to java.io.Serializable when use second level cache

### ISSUE THREAD

**Issue by billtian** [GeoLatte/geolatte-geom#132]
when we use CoordinateReferenceSystem as our entities' property and enable L2 cache , will thrown "org.geolatte.geom.crs.Geographic2DCoordinateReferenceSystem cannot be cast to java.io.Serializable"

see [this](https://github.com/billtian/geolatte-test) test repos.

Thanks !

**Comment by maesenka** [comment]
This will be released as 1.8.1 in a couple of days
