### ISSUE TITLE
BoundingBox on Feature and FeatureCollection

### ISSUE THREAD

**Issue by sebisteiner** [GeoLatte/geolatte-geom#145]
At the moment the `Feature`and `FeatureCollection` implementations are missing the optional `bbox` member:
https://datatracker.ietf.org/doc/html/rfc7946#page-12

Is this intentional or can it be extended?

**Comment by maesenka** [comment]
I didn't get around to supporting it. So, yes. It can be extended

**Comment by sebisteiner** [comment]
I made a proposal here: https://github.com/GeoLatte/geolatte-geom/pull/146

**Comment by maesenka** [comment]
This is now in master
