### ISSUE TITLE
JTS Version question

### ISSUE THREAD

**Issue by instagibb** [GeoLatte/geolatte-geom#149]
In the parent geolatte pom the JTS version is defined by a property 
```
<properties>
<jts-core.version>1.18.0</jts-core.version>
</properties>
```

However in the released versions on the Maven repositories the pom has a version range defined?

```
<properties>
<jts-core.version>[1.18.0, 1.19.0)</jts-core.version>
</properties>
```

This means that it ends up having a jts-core dependency of any later version of 1.18.x below 1.19.0? 

My question is when does the `jts-core.version` property get modified?

**Comment by maesenka** [comment]
When there is a need for it. We don't try to track JTS closely. We need to be mindful that updating JTS doesn't break our API.

**Comment by instagibb** [comment]
My question was more about the build process and does it modify the version?

Why is it a range of versions in the compiled jar in the official maven repositories when the source here suggests it is locked to a specific version?
