### ISSUE TITLE
Issues about how to use class SDOGeometry 

### ISSUE THREAD

**Issue by dtneverdie** [GeoLatte/geolatte-geom#154]
I found that there is a SDOGeometry class in geom which might work well in oracle. I tried to construct a SDOGeometry like how u show in test but there is no SDOGeometryHelper in Maven's geolatte-geom, and SDOGtype and SDOPoint can not be accessde from outside. I wanna know how to new a SDOGeometry class.

**Comment by maesenka** [comment]
You should create geometries as explained in the README and then use the Encoders class:
```
import org.geolatte.geom.codec.db.oracle.Encoders;
....
SDOGeometry encode = Encoders.encode(geom);
```
