### ISSUE TITLE
Error in the documentation of README for the constructor of type Point

### ISSUE THREAD

**Issue by opticSquid** [GeoLatte/geolatte-geom#167]
In the README Section of this repository there is a section for `creating geometries` under `Quick Start`. Here is the image for indication:

![image](https://github.com/GeoLatte/geolatte-geom/assets/59192460/ffb85823-c865-416c-a534-148b03debb75)
 There are 2 typo problems in this line:
 
![annotated](https://github.com/GeoLatte/geolatte-geom/assets/59192460/bdda27ba-611c-4c70-8358-947d419fe4bb)

The underlined line would be:
```java
  Point<G2D> pnt=Point(g(4.33,53.21),WGS84);
```
Changes:
- constructor would start with Uppercase letter: ~point~ to **Point**
- and the arguements passed will be swapped in position ~point(WGS84,g(4.33,53.21))~ to **Point(g(4.33,53.21),WGS84)**

### Why this change is important
People who will be using this library for the first time will inevitabely go through the readme file to understand how to work with this library if the first line only contains a typo it gives a bad impression and user may switch to another library thinking it is not a good library which is not the case with this library so, this change is urgently required. This a urgent non-trivial change if you assign it to me I will do it. It would take 2 mins.

**Comment by maesenka** [comment]
The code in the README is correct. It makes us of the static factory methods in the DSL package.
