### ISSUE TITLE
How does geolatte work among over thousands of Lon&Lat Points

### ISSUE THREAD

**Issue by kensinzl** [GeoLatte/geolatte-geom#170]
Dear

I use this package for Oracle Spatial type. Meanwhile, I am using Java JPA for this.
```
  <dependency>
      <groupId>org.geolatte</groupId>
      <artifactId>geolatte-geom</artifactId>
      <version>1.9.1</version>
  </dependency>
```
This is the table structure
```
GRID_POINT_BOUNDARY {
  BOUNDARY_ID	NUMBER(19,0)
  BOUNDARY_DEF	SDO_GEOMETRY
  NAME	VARCHAR2(255 BYTE)
}
```

I have a Polygon object which has over 6,000 Lon&Lat Points.

- Good news, if I am using JPA em.persist(GRID_POINT_BOUNDARY object), it works well,
- But for me, this JPA will eventually be parsed into the pure SQL query, and the parsed SQL query is 
```
insert 
into
    GRID_POINT_BOUNDARY
    (BOUNDARY_DEF,NAME,BOUNDARY_ID) 
values
    (?,?,?)
```
So my question is 

- From the SQL query, if the point size is over 1000, Oracle will throw the exception to show over the max argument, it makes sense
```
insert into grid_point_boundary (boundary_id, boundary_def, name) values 
(1720306325, 
MDSYS.SDO_GEOMETRY(2003, 4326, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1), MDSYS.SDO_ORDINATE_ARRAY(176.520435982979, -37.3548683162894, ........ repeat the points), 'Name')
```

- I am curious how does the geolatte handle this issue to work around the oracle?

Any information is welcome

**Comment by kensinzl** [comment]
may I check could someone please have a look at this ticket? thank you so much.

**Comment by maesenka** [comment]
the answer is that Geolatte (and Hibernate Spatial) use prepared statements. The geometry object is constructed and bound to the prepared statement. The geometry object is not turned into a textual presentation that needs to be parsed as SQL.

**Comment by kensinzl** [comment]
@maesenka thanks for your response.

the answer is that Geolatte (and Hibernate Spatial) use prepared statements.
=> Here, I want to double check could you please share the example for the prepared statements you mentioned? is it just a normal insert query? thanks so much

**Comment by kensinzl** [comment]
@maesenka can I check how is going on for the above message? thank you so much.
