### ISSUE TITLE
Infinite loop in WKT parser with invalid polygon

### ISSUE THREAD

**Issue by ssaarela** [GeoLatte/geolatte-geom#31]
An invalid polygon causes WKT parser to loop until heap size is reached. E.g.  

Wkt.newDecoder(Wkt.Dialect.POSTGIS_EWKT_1).decode("POLYGON( 24.881973486328125 60.15671327918588, 24.936218481445312 60.160642536827424, 24.978103857421875 60.16696253094966, 24.881973486328125 60.15671327918588 )");

**Comment by maesenka** [comment]
Could you post the stacktrace?

**Comment by ssaarela** [comment]
Getting a stack trace takes quite a lot of time to fill the heap, but I debugged it to 

PostgisWktDecoder#179: while (!matchesCloseList())

decodeLinearRingText() returns empty LinearRings for ever.

**Comment by maesenka** [comment]
Thanks, that’s what I needed.

**Comment by maesenka** [comment]
Fixed and pushed as version 0.15
