### ISSUE TITLE
Encoder for SQLServer WKB does not work for Polygons

### ISSUE THREAD

**Issue by securityLast** [GeoLatte/geolatte-geom#35]
I am using Hibernate 5.0.4 and it is failing to read my polygons from the database.  The encoder works  for Points and lines but not for Polygons.  In Hibernate I get an Index 0 size 0 failure.  I setup a junit test to encode a geometry to sql byte array then decode.  The encode outputs an byte array that is invalid - can't get SQL Server functions to decode - and the decode throws an exception.

**Comment by maesenka** [comment]
Same here. Could you share the tests?

**Comment by maesenka** [comment]
Never mind. I see you already included them in #35

**Comment by maesenka** [comment]
I've diagnosed the problems, and will fix them in the next few days.

**Comment by maesenka** [comment]
Fixed by 34fc26d3d0781f9591d7bd21ff22a3b9795d3d64

**Comment by securityLast** [comment]
Thanks for such a quick response!
