### ISSUE TITLE
Custom VerticalCoordinateReferenceSystem not possible

### ISSUE THREAD

**Issue by michikommader** [GeoLatte/geolatte-geom#37]
Two things regarding VerticalCoordinateReferenceSystems
1. The constructor of a `org.geolatte.geom.crs.VerticalCoordinateReferenceSystem` is protected. How to manually construct such a system?
2. What does the `datumtype` of a `org.geolatte.geom.crs.VerticalDatum` refer to? The documentation is missing.

**Comment by maesenka** [comment]
Currently you can only construct a VerticalCoordinateReferenceSystem with the factory method CoordinateReferenceSystems.mkVertical(LinearUnit)

I'll consider adding other factory methods, or make the constructor public

As for the meaning of VerticalDatum, it is a term used in geodesy to indicate how elevation measurement is to be interpreted (see e.g. https://en.wikipedia.org/wiki/Geodetic_datum#Vertical_datum). It is modeled here as in the OGC specification "OpenGIS Implementation Specification: Coordinate Transformation Services" (rev. 1.00)"
