### ISSUE TITLE
Unable to define additional CoordinateReferenceSystems in the CrsRegistry

### ISSUE THREAD

**Issue by sayresVT** [GeoLatte/geolatte-geom#39]
Currently there doesn't seem to be any extension point for defining additional CoordinateReferenceSystems to be used by the CrsRegistry.  As a workaround, you currently need to: 
- Hand modify the spatial_ref_sys.txt bundled in the JAR 
- or Use the parent ClassLoader to load a modified version of the spatial_ref_sys.txt before CrsRegistry.class is loaded

It would be nice to have the ability to more easily specify additional coordinate reference systems to be used by the CrsRegistry.

**Comment by Infrag** [comment]
To me it seems easier to use reflections to add custom CRS.

**Comment by matthias24** [comment]
This is exactly my problem. The simplest solution would be to set the method addDefinition at line 84 in the class CrsRegistry from private to public. Reflection is a nice workarround for this.
But the best solution in my opinion would be, to add a method to the class CrsRegistry, to add a factory, which can supply the registry with CRS-Systems. This factory could maybe load a CRS-System lazy, when it is ordered via the EPSG-Code.

**Comment by maesenka** [comment]
I provided a public method registerCoordinateReferenceSystem() to solve this issue. 

I also updated the embedded spatial ref. systems definition file.
