### ISSUE TITLE
Wrong character in spatial_ref_sys.txt

### ISSUE THREAD

**Issue by stiffler17** [GeoLatte/geolatte-geom#45]
Hi!

I had the issue #41 with the wrong SRID for 3857 and so I updated to version 1.0.3. Now I get a warning from wilfly!

09:36:39,716 WARN  [org.geolatte.geom.crs.CrsRegistry] (default task-49) Can't parse srid 3857 ('PROJCS[..

I've downloaded the source an looked to the spatial_ref_sys.txt.
![error](https://cloud.githubusercontent.com/assets/14252961/17243545/a7e2a880-557d-11e6-872c-696d1f259624.PNG)

**Comment by maesenka** [comment]
Fix is now released as 1.0.4
