### ISSUE TITLE
Upgrade JTS dependency

### ISSUE THREAD

**Issue by ridoo** [GeoLatte/geolatte-geom#65]
Is there a plan to use recent version `1.15.0` of JTS? 

Please note that JTS has been adopted by [LocationTech](http://www.locationtech.org/). Therefore, packaging has been changed from `com.vividsolutions` to `org.locationtech`. Here's a simple [migration guide](https://github.com/locationtech/jts/blob/master/MIGRATION.md) for migration.

I am aware of the de-emphasize statement. However it might be nice to have a geolatte version available which imports the re-packaged classes in case [JTS](https://github.com/GeoLatte/geolatte-geom/blob/master/geom/src/main/java/org/geolatte/geom/jts/JTS.java) interoperability will stay part of the features list.

**Comment by maesenka** [comment]
We will definitely keep JTS interop, and keep in step with more recent versions.

**Comment by maesenka** [comment]
Resolved by be7677f46f243a5a97b03eb06b90d44e28cbca13
