### ISSUE TITLE
GeometrySerializer does not override serializeWithType

### ISSUE THREAD

**Issue by sbrandwoo** [GeoLatte/geolatte-geom#66]
The currently implementation of `GeometrySerializer` doesn't override the `serializeWithType` method. This has caused me some issues when trying to store geolatte objects in Redis, where the deserialization process tries to use `serializeWithType` to convert JSON strings back into Java objects. 

Is this something that could be added?

**Comment by maesenka** [comment]
Yes, this could be added. Could you do a PR for this? If not, it will take some time. 

In any case, I'll add a ticket for this.

**Comment by maesenka** [comment]
@sbrandwoo Could you check if this implementation does the job?

I haven't found a good way to test this.
