### ISSUE TITLE
DecimalDegreeTest.testDMS failed because of locale

### ISSUE THREAD

**Issue by Furcube** [GeoLatte/geolatte-geom#73]
EIDT: in master branch
Cause is DecimalDegree.toDMS which is using String.format with default locale
In russian locale decimal separator is comma, this will result in test failing with result:
```
Expected :4° 20' 30.00''E 50° 10' 20.00''N
Actual   :4° 20' 30,00''E 50° 10' 20,00''N
```
I did a quick-fix for myself adding Locale.US to that call of String.format, But not sure if this is right solution.

**Comment by maesenka** [comment]
Thanks for the report. I solved it in (almost) the same way (using Locale.ROOT rather than US)
