### ISSUE TITLE
Support for 2D+1 coordinate system

### ISSUE THREAD

**Issue by FlorianFehring** [GeoLatte/geolatte-geom#89]
Hello,

I have some data in EPSG: 5555. These are some 3D building models. When trying to load them a "NotSupportedException" occures from CartesianCoordinateSystem3D.extend. This is because of the PostgisWkbDecoder.readCrs method detects that this coordinate system has a z axis (hasZ=true) but also CrsRegistry.getCoordinateReferenceSystemForEPSG() delivers a CoordinateReferenceSystem that has allready 3 axis. 
The following code checks if(hasZ==true) and then tries to add a verticalSystem. But scince there is allready a z-axis in the CoordinateReferenceSystem it tries do make a C3DM out of it, which could not work because the provided 4th axis is of type VerticalStraightLineAxis and not the supported MeasureStraightLineAxis.

I simply solved this for my usecase by replaceing (in PostgisWkbDecoder):

if (hasZ) {
            crsDeclared = addVerticalSystem(crsDeclared, Unit.METER);
}

with:

if (hasZ && crsDeclared.getCoordinateDimension() < 3) {
            crsDeclared = addVerticalSystem(crsDeclared, Unit.METER);
        }

Scince i'am a beginner in this geodata stuff, i think there would be a better solution.

I use:
- postgres 11 / postgis 3
- hibernate spatial 5.4.8
- geolatte-geom 1.5 snapshot (28.11.19)

**Comment by maesenka** [comment]
The code assumes (wrongly) that the `CrsRegistry` always returns a 2D reference system.  I'll look into it
