### ISSUE TITLE
FeatureSerializationTest is performing DeSerialization

### ISSUE THREAD

**Issue by vchrisb** [GeoLatte/geolatte-geom#90]
The FeatureSerializationTest Class is doing `testDeSerialize()` rather than a `testSerialize()`

https://github.com/GeoLatte/geolatte-geom/blob/master/json/src/test/java/org/geolatte/geom/json/FeatureSerializationTest.java#L22

**Comment by vchrisb** [comment]
thx @maesenka but this only changes the method name but the test is implementing DeSerialization rather Serialization.

**Comment by maesenka** [comment]
The test checks that a feature is correctly **serialized**. The test was fine, but he name was incorrect.
