### ISSUE TITLE
Are spatial operations supported?

### ISSUE THREAD

**Issue by russellhoff** [GeoLatte/geolatte-geom#99]
I've been looking for spatial operations such as difference, buffer or intersection. Those operations actually exist on JTS, but are they in Geolatte?

Thanks

**Comment by russellhoff** [comment]
I've found a class which contains all the required methods: `org.geolatte.geom.JTSGeometryOperations`.

Unfortunately, I'm using geometry objects projected on the geographic coordinate reference system. What can I do?

**Comment by maesenka** [comment]
Hi Jon,

Currently Geolatte-geom delegates most operations to JTS. These operations
are only supported on the planar plane.  I would love to add support for
geometry operations on the ellipsoids, but haven't found the time to do it.

Regards,

Karel

**Comment by russellhoff** [comment]
I'd like to add it and create a PR
